### ISSUE TITLE
Case sensitivity for filenames 

### ISSUE THREAD

**Issue by GWRon** [davecamp/BMax-Shader-Framework#2]
BMK is case sensitive when it comes to filenames compared to modulenames.

On Linux "srs.mod/shaderframework.mod" is different to "srs.mod/ShaderFramework.mod". With the first one BMK is looking for a "shaderframework.bmx" while the second variant leads to a search for "ShaderFramework.bmx".
So consistency is needed either install instructions - or keep consistent with all the other modules and use lowercase for the module main file (and maybe even the others).

**Comment by GWRon** [comment]
you do not need to lower-case the `import Brl.LinkedList` (and the likes) statements.

The `import modscope.module` and `module` commands are ignoring the case sensitivity. Only direct file imports (`import "MyFile.bmx"`) and real directory names ("blitzmax/mod/MyModScope.mod/SuperDuperModule.mod") are taken into consideration. So `import path` needs to have the `path` written in the way it is stored on the drive. 

Excuse the wordy explanation style. Being concise is more difficult in foreign languages.

**Comment by davecamp** [comment]
That's ok I understand what you mean.
I remember case-sensitivity doesn't matter within the BMax code itself - I must admit I went a little over the top :O)
