### ISSUE TITLE
Shader placeholder-variables

### ISSUE THREAD

**Issue by GWRon** [davecamp/BMax-Shader-Framework#3]
Maybe emphasize the placeholders a bit more?

old
```HLSL
VS_OUT VSMain(VS_IN vsIn) {
   VS_OUT vsOut;
   vsOut.pos = mul(BMaxProjectionMatrix, float4(vsIn.pos, 1.0f));
   vsOut.col = vsIn.col;
   vsOut.uv = vsIn.uv;
   return vsOut;
}
```

proposed:
```HLSL
VS_OUT VSMain(VS_IN vsIn) {
   VS_OUT vsOut;
   vsOut.pos = mul(%BMAXPROJECTIONMATRIX%, float4(vsIn.pos, 1.0f));
   vsOut.col = vsIn.col;
   vsOut.uv = vsIn.uv;
   return vsOut;
}
```
The `%BMAXPROJECTIONMATRIX%` might look "known" to most programmers (bash scripts and the likes). The UPPERCASE makes it pop out. Also `__BMAXPROJECTIONMATRIX__` might look like a way to go.

```HLSL
VS_OUT VSMain(VS_IN vsIn) {
   VS_OUT vsOut;
   vsOut.pos = mul(__BMAXPROJECTIONMATRIX__, float4(vsIn.pos, 1.0f));
   vsOut.col = vsIn.col;
   vsOut.uv = vsIn.uv;
   return vsOut;
}
```
But this looks more like an (uber) global available constant.

**Comment by davecamp** [comment]
Thanks for your input.
I've currently gone for BMAX_PROJECTION_MATRIX style.
Unfortunately the 'percent symbol' cannot be used in shader code for variables names.

**Comment by GWRon** [comment]
@ percent symbol
Is there a reason? I mean uf the code is not evaluated before (`execute(string.replace(bla,blubb))`) then it should not matter what chars are used.
But nvm ... you already addressed the whole issue. Thanks

**Comment by davecamp** [comment]
@ percent symbol
I don't pre-process the shader code in any way to keep things as standard and straight-forward as could be. That's not to say in the future that running a pre-process of some kind is out of the question, just that there's no real need at this time.

I use the default API reflection so the shader code has to be valid according to the glsl or hlsl standards: GLSL 1.2, HLSL 3.0 for D3D9, and HLSL 5.0 for D3D11.

**Comment by GWRon** [comment]
Ahh ok ... so I just assumed something wrong - again.
Thought it is like a "whatever text" that gets feed somewhen to a shader "processor/compiler" (so you could glue things together, replace words, ...).

Thanks for the clarification.

**Comment by davecamp** [comment]
I'll close this one for the time being.
